blueprint:
  name: "Dehumidifier Control (Solar-Powered)"
  description: "Guaranteed working version for HA 2024.12"
  domain: automation
  input:
    humidity_sensor:
      name: "Humidity Sensor"
      selector:
        entity:
          domain: sensor
          device_class: humidity
    dehumidifier:
      name: "Dehumidifier Entity"
      selector:
        entity:
          domain: switch
    solar_sensor:
      name: "Solar Production Sensor"
      selector:
        entity:
          domain: sensor
    min_humidity:
      name: "Activate Above (%)"
      default: 55
      selector:
        number:
          min: 30
          max: 80
          step: 1
          mode: box
    max_humidity:
      name: "Deactivate Below (%)"
      default: 45
      selector:
        number:
          min: 30
          max: 80
          step: 1
          mode: box
    min_solar:
      name: "Minimum Solar (W)"
      default: 200
      selector:
        number:
          min: 0
          max: 3000
          step: 50
          mode: box

trigger:
  - platform: state
    entity_id: !input humidity_sensor
    attribute: state

condition:
  - condition: and
    conditions:
      - condition: template
        value_template: >-
          {{ float(states(input.humidity_sensor)) > float(input.min_humidity) }}
      - condition: template
        value_template: >-
          {{ float(states(input.solar_sensor)) >= float(input.min_solar) }}

action:
  - service: switch.turn_on
    target:
      entity_id: !input dehumidifier
  - wait_for_trigger:
      - platform: template
        value_template: >-
          {{ float(states(input.humidity_sensor)) < float(input.max_humidity) }}
    timeout: "02:00:00"
  - service: switch.turn_off
    target:
      entity_id: !input dehumidifier
