blueprint:
  name: "Dehumidifier Control (No Templates)"
  description: "Simplified humidity control without Jinja2 templates."
  domain: automation
  input:
    humidity_sensor:
      name: "Humidity Sensor"
      selector:
        entity:
          domain: sensor
          device_class: humidity
    dehumidifier:
      name: "Dehumidifier Switch"
      selector:
        entity:
          domain: switch
    min_humidity:
      name: "Activate Above (%)"
      default: 55
      selector:
        number:
          min: 30
          max: 80
          step: 5
    max_humidity:
      name: "Deactivate Below (%)"
      default: 45
      selector:
        number:
          min: 30
          max: 80
          step: 5

trigger:
  - platform: numeric_state
    entity_id: input.humidity_sensor
    above: input.min_humidity
    for:
      minutes: 10  # Prevents rapid cycling

condition:
  - condition: numeric_state
    entity_id: input.humidity_sensor
    above: input.min_humidity  # Re-check in case value changed

action:
  - service: switch.turn_on
    target:
      entity_id: input.dehumidifier
  - wait_for_trigger:
      - platform: numeric_state
        entity_id: input.humidity_sensor
        below: input.max_humidity
    timeout: "02:00:00"  # Max runtime
  - service: switch.turn_off
    target:
      entity_id: input.dehumidifier
