blueprint:
  name: "Tesla Solar Charging w/ Forecast & Modes (GoodWe)"
  description: "Smart charging with solar forecasts, multiple modes, and battery protection."
  domain: automation
  input:
    # Required Entities
    tesla_charger:
      name: "Tesla Charger Entity"
      selector:
        entity:
          domain: binary_sensor
          device_class: plug
    solar_production:
      name: "Solar Production Sensor"
      selector:
        entity:
          domain: sensor
    house_consumption:
      name: "House Consumption Sensor"
      selector:
        entity:
          domain: sensor
    battery_soc:
      name: "Battery SOC Sensor"
      selector:
        entity:
          domain: sensor
    grid_import:
      name: "Grid Import Sensor"
      selector:
        entity:
          domain: sensor
    # Forecast Integration (Solcast/OpenWeather)
    solar_forecast:
      name: "Solar Forecast Sensor"
      selector:
        entity:
          domain: sensor
      description: "e.g., solcast.total_kwh_forecast_today"
    # User-Selectable Mode
    charging_mode:
      name: "Charging Mode"
      selector:
        select:
          options:
            - "Surplus Only (PV+Battery)"
            - "Trip Prep (Charge to X%)"
            - "Stop (No Charging)"
      default: "Surplus Only (PV+Battery)"
    # Thresholds
    trip_soc_target:
      name: "Trip SOC Target (%)"
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 5
      description: "Only used in 'Trip Prep' mode"
trigger:
  # Re-evaluate every 15 mins or when solar/forecast changes
  - platform: time_pattern
    minutes: "/15"
  - platform: state
    entity_id: !input solar_forecast
  - platform:

