blueprint:
  name: "Tesla Solar Charging w/ Forecast & Modes (GoodWe)"
  description: "Smart charging with solar forecasts, multiple modes, and battery protection."
  domain: automation
  input:
    # Required Entities
    tesla_charger:
      name: "Tesla Charger Entity"
      selector:
        entity:
          domain: binary_sensor
          device_class: plug
    solar_production:
      name: "Solar Production Sensor"
      selector:
        entity:
          domain: sensor
    house_consumption:
      name: "House Consumption Sensor"
      selector:
        entity:
          domain: sensor
    battery_soc:
      name: "Battery SOC Sensor"
      selector:
        entity:
          domain: sensor
    grid_import:
      name: "Grid Import Sensor"
      selector:
        entity:
          domain: sensor
    # Forecast Integration (Solcast/OpenWeather)
    solar_forecast:
      name: "Solar Forecast Sensor"
      selector:
        entity:
          domain: sensor
      description: "e.g., solcast.total_kwh_forecast_today"
    # User-Selectable Mode
    charging_mode:
      name: "Charging Mode"
      selector:
        select:
          options:
            - "Surplus Only (PV+Battery)"
            - "Trip Prep (Charge to X%)"
            - "Stop (No Charging)"
      default: "Surplus Only (PV+Battery)"
    # Thresholds
    trip_soc_target:
      name: "Trip SOC Target (%)"
      default: 90
      selector:
        number:
          min: 50
          max: 100
          step: 5
      description: "Only used in 'Trip Prep' mode"
trigger:
  # Re-evaluate every 15 mins or when solar/forecast changes
  - platform: time_pattern
    minutes: "/15"
  - platform: state
    entity_id: !input solar_forecast
  - platform: state
    entity_id: !input solar_production
  - platform: state
    entity_id: !input house_consumption
condition:
  # Only run if Tesla is plugged in
  - condition: state
    entity_id: !input tesla_charger
    state: "on"
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ is_state('input_select.charging_mode', 'Surplus Only (PV+Battery)') }}"
        sequence:
          - service: variable.set_variable
            data:
              entity_id: var.ev_charge_policy
              value: "Surplus"
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (states('sensor.solar_production') | float(0) - states('sensor.house_consumption') | float(0) > 3000) or
                         (states('sensor.solar_forecast') | float(0) > 5 and
                          states('sensor.battery_soc') | float(0) >= 75) }}
                sequence:
                  - service: tesla.start_charging
                    target:
                      entity_id: !input tesla_charger
                  - service: notify.mobile_app
                    data:
                      message: >
                        ⚡ Charging STARTED (Mode: Surplus).
                        Solar: {{ states('sensor.solar_production') }}W →
                        House Consumption: {{ states('sensor.house_consumption') }}W →
                        Surplus: {{ states('sensor.solar_production') | float(0) - states('sensor.house_consumption') | float(0) }}W →
                        Forecast: {{ states('sensor.solar_forecast') }}kWh
              default:
                - service: tesla.stop_charging
                  target:
                    entity_id: !input tesla_charger
      - conditions:
          - condition: template
            value_template: "{{ is_state('input_select.charging_mode', 'Trip Prep (Charge to X%)') }}"
        sequence:
          - service: variable.set_variable
            data:
              entity_id: var.ev_charge_policy
              value: "TripPrep"
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states('sensor.tesla_battery_level') | float(0) < (input.trip_soc_target | float(0)) }}
                sequence:
                  - service: tesla.start_charging
                    target:
                      entity_id: !input tesla_charger
                  - service: notify.mobile_app
                    data:
                      message: >
                        🚗 Charging to {{ input.trip_soc_target }}% (Trip Prep Mode).
                        Current: {{ states('sensor.tesla_battery_level') }}%
              default: []
      - conditions:
          - condition: template
            value_template: "{{ is_state('input_select.charging_mode', 'Stop (No Charging)') }}"
        sequence:
          - service: tesla.stop_charging
            target:
              entity_id: !input tesla_charger
          - service: variable.set_variable
            data:
              entity_id: var.ev_charge_policy
              value: "Stopped"
  default: []
